# Generated by Django 4.2.28 on 2026-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
        ('events', '0003_event_checkin_and_participant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participating_organizations',
            field=models.ManyToManyField(blank=True, related_name='participating_events', to='organizations.organization'),
        ),
    ]
