# Generated by Django 4.2.30 on 2026-06-16 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_by_username', models.CharField(blank=True, max_length=150)),
                ('backup_name', models.CharField(blank=True, max_length=255)),
                ('backup_created_at', models.CharField(blank=True, max_length=64)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('source_environment', models.CharField(blank=True, max_length=32)),
                ('target_environment', models.CharField(blank=True, max_length=32)),
                ('environment_override', models.BooleanField(default=False)),
                ('result', models.CharField(choices=[('validated', 'Validated (not applied)'), ('pending', 'Apply started'), ('success', 'Restored'), ('failed', 'Failed'), ('rolled_back', 'Failed — rolled back'), ('rejected', 'Rejected (validation)')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='restore_created_idx'), models.Index(fields=['result'], name='restore_result_idx')],
            },
        ),
    ]
