# Generated by Django 4.2.27 on 2026-01-27 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0002_projectindicator_quarterly_targets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndicatorOrganizationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('q2_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('q3_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('q4_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('target_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('baseline_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_indicator_targets', to='organizations.organization')),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_targets', to='projects.projectindicator')),
            ],
            options={
                'unique_together': {('project_indicator', 'organization')},
            },
        ),
    ]
