# Generated by Django 4.2.27 on 2026-05-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_hierarchy_overrides'),
        ('projects', '0003_projectindicatororganizationtarget'),
    ]

    operations = []
