# Generated by Django 4.2.30 on 2026-05-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
        ('projects', '0004_merge_20260527_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrganizationHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_hierarchy_child_links', to='organizations.organization')),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_hierarchy_parent_links', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_hierarchy_links', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'parent_organization_id', 'child_organization_id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('coordinator', 'Coordinator'), ('sub_grantee', 'Sub-grantee'), ('implementing_partner', 'Implementing Partner'), ('data_reviewer', 'Data Reviewer'), ('funder', 'Funder'), ('other', 'Other')], default='implementing_partner', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('implementation_scope', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_organizations', to='projects.project')),
            ],
            options={
                'ordering': ['project_id', 'organization_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectorganizationhierarchy',
            constraint=models.CheckConstraint(check=models.Q(('parent_organization', models.F('child_organization')), _negated=True), name='project_hierarchy_parent_child_must_differ'),
        ),
        migrations.AlterUniqueTogether(
            name='projectorganizationhierarchy',
            unique_together={('project', 'parent_organization', 'child_organization')},
        ),
        migrations.AlterUniqueTogether(
            name='projectorganization',
            unique_together={('project', 'organization')},
        ),
    ]
