# Generated by Django 4.2.30 on 2026-05-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
        ('projects', '0006_backfill_project_scope_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndicatorDisaggregationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_key', models.CharField(max_length=64)),
                ('display_label', models.CharField(blank=True, max_length=128)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_indicator_disaggregation_rules', to='organizations.organization')),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaggregation_rules', to='projects.projectindicator')),
            ],
            options={
                'ordering': ['project_indicator_id', 'sort_order', 'id'],
                'unique_together': {('project_indicator', 'organization', 'dimension_key')},
            },
        ),
        migrations.CreateModel(
            name='ProjectIndicatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_source', models.CharField(choices=[('project_scope', 'Project Scope'), ('organization_target', 'Organization Target'), ('manual', 'Manual'), ('aggregate_history', 'Aggregate History')], default='project_scope', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_indicator_assignments', to='organizations.organization')),
                ('project_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='projects.projectindicator')),
            ],
            options={
                'ordering': ['project_indicator_id', 'organization_id'],
                'unique_together': {('project_indicator', 'organization')},
            },
        ),
    ]
