# Generated by Django 4.2.30 on 2026-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='client_organizations', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
