# Generated by Django 4.2.30 on 2026-06-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_is_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectindicator',
            name='target_group',
            field=models.CharField(blank=True, help_text='e.g. PLHIV, AYP (10-24), Women, KP, MSM, FSW', max_length=255),
        ),
    ]
