# Generated by Django 4.2.30 on 2026-06-09 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0016_split_districts_localities'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users explicitly assigned to this project. Non-admin users only see data for projects they are assigned to.', related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
