# Generated by Django 4.2.30 on 2026-07-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_indicator_denominator_indicator'),
        ('projects', '0019_workbook_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindicator',
            name='target_source_indicator',
            field=models.ForeignKey(blank=True, help_text='Source indicator whose achieved value drives this target.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indicators.indicator'),
        ),
        migrations.AddField(
            model_name='projectindicator',
            name='target_source_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of the source achieved value (percentage mode).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='projectindicator',
            name='target_source_type',
            field=models.CharField(choices=[('fixed', 'Fixed target'), ('derived', 'Achieved value of another indicator'), ('percentage', "Percentage of another indicator's achieved value")], default='fixed', max_length=12),
        ),
        migrations.AddField(
            model_name='projectindicatororganizationtarget',
            name='target_source_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='indicators.indicator'),
        ),
        migrations.AddField(
            model_name='projectindicatororganizationtarget',
            name='target_source_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='projectindicatororganizationtarget',
            name='target_source_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed target'), ('derived', 'Achieved value of another indicator'), ('percentage', "Percentage of another indicator's achieved value")], help_text='Overrides the project-indicator target source for this coordinator; null = inherit.', max_length=12, null=True),
        ),
    ]
