# Generated by Django 4.2.30 on 2026-06-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_dashboard_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0019_workbook_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbookLayoutSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('org', 'Organisation workbook'), ('coordinator', 'Coordinator workbook')], default='org', max_length=12)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('training', 'Training')], default='live', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_label', models.CharField(blank=True, default='', max_length=64)),
                ('layout_name', models.CharField(blank=True, default='', max_length=255)),
                ('layout_version', models.CharField(blank=True, default='', max_length=64)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workbook_layout_snapshots', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbook_layout_snapshots', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbook_layout_snapshots', to='projects.project')),
                ('source_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='projects.workbooklayout')),
            ],
            options={
                'ordering': ['-period_start', 'organization_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workbooklayoutsnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'organization', 'kind', 'mode', 'period_start', 'period_end'), name='unique_workbook_layout_snapshot_per_period'),
        ),
    ]
