# Generated by Django 4.2.30 on 2026-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectindicator_target_source_indicator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ['due_date', 'id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='projectactivity',
            options={'ordering': ['start_date', 'title', 'id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', '-priority', 'id']},
        ),
    ]
