# Generated by Django 4.2.28 on 2026-02-05 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('headquarters', 'Headquarters'), ('regional', 'Regional Office'), ('district', 'District Office'), ('partner', 'Partner Organization'), ('ngo', 'NGO'), ('government', 'Government'), ('funder', 'Funder')], default='district', max_length=20),
        ),
    ]
