# Generated by Django 4.2.30 on 2026-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='dashboard_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
