# Generated by Django 4.2.30 on 2026-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_add_dashboard_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name', 'id']},
        ),
    ]
