# Generated by Django 4.2.30 on 2026-07-08 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0010_indicator_denominator_indicator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_projectindicator_target_source_indicator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_number', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, default='')),
                ('chart_type', models.CharField(choices=[('achieved_vs_target', 'Achieved vs target bar'), ('grouped_bar', 'Grouped bar'), ('stacked_bar', 'Stacked bar'), ('horizontal_bar', 'Horizontal ranked bar'), ('line', 'Line (quarterly trend)'), ('pie', 'Pie / donut'), ('heatmap', 'Heatmap (age × sex)'), ('cascade', 'Cascade / funnel'), ('table', 'Table')], default='grouped_bar', max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('aggregation_method', models.CharField(choices=[('sum', 'Sum'), ('count', 'Count of reporting orgs'), ('average', 'Average')], default='sum', max_length=16)),
                ('grouping_dimension', models.CharField(choices=[('none', 'None'), ('organization', 'CSO / organization'), ('coordinator', 'Coordinator organization'), ('indicator', 'Indicator (e.g. message type)'), ('sex', 'Sex'), ('age', 'Age range'), ('key_population', 'Key population / category'), ('district', 'District'), ('period', 'Reporting period (trend)')], default='organization', max_length=24)),
                ('secondary_grouping_dimension', models.CharField(choices=[('none', 'None'), ('organization', 'CSO / organization'), ('coordinator', 'Coordinator organization'), ('indicator', 'Indicator (e.g. message type)'), ('sex', 'Sex'), ('age', 'Age range'), ('key_population', 'Key population / category'), ('district', 'District'), ('period', 'Reporting period (trend)')], default='none', max_length=24)),
                ('target_mode', models.CharField(choices=[('none', 'No target'), ('org_quarter', 'Per-organization quarterly target'), ('project', 'Project indicator target')], default='none', max_length=16)),
                ('calculation_mode', models.CharField(choices=[('none', 'None'), ('achievement_percent', 'Achievement % (achieved / target × 100)'), ('ratio_percent', 'Ratio % (numerator / denominator × 100)')], default='none', max_length=24)),
                ('narrative_template', models.TextField(blank=True, default='', help_text='Optional templated narrative. Placeholders: {total}, {target}, {achievement_percent}, {top_org}, {org_count}.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('funder', models.CharField(blank=True, default='', max_length=255)),
                ('reporting_year', models.CharField(blank=True, default='', help_text='e.g. "2025/26" (Botswana fiscal year label).', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funder_report_templates', to='projects.project')),
            ],
            options={
                'ordering': ['-reporting_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('objective_label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='funder_reports.reporttemplate')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportFigureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('chart_config_json', models.JSONField(blank=True, default=dict)),
                ('narrative_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('published', 'Published')], default='draft', max_length=16)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project')),
                ('report_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='funder_reports.reportfigure')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFigureIndicatorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('achieved', 'Achieved'), ('target', 'Target'), ('numerator', 'Numerator'), ('denominator', 'Denominator'), ('category', 'Category (its own series/bar)'), ('comparison', 'Comparison'), ('excluded', 'Excluded'), ('supporting_narrative', 'Supporting narrative')], default='achieved', max_length=24)),
                ('label_override', models.CharField(blank=True, default='', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('include_in_total', models.BooleanField(default=True)),
                ('calculation_role', models.CharField(blank=True, default='', help_text='Free-form tag used by calculation_mode (e.g. which side of a ratio).', max_length=24)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_figure_mappings', to='indicators.indicator')),
                ('report_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='funder_reports.reportfigure')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportFigureFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_name', models.CharField(choices=[('none', 'None'), ('organization', 'CSO / organization'), ('coordinator', 'Coordinator organization'), ('indicator', 'Indicator (e.g. message type)'), ('sex', 'Sex'), ('age', 'Age range'), ('key_population', 'Key population / category'), ('district', 'District'), ('period', 'Reporting period (trend)')], max_length=24)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('exclude_values', models.JSONField(blank=True, default=list)),
                ('filter_mode', models.CharField(choices=[('include', 'Include only'), ('exclude', 'Exclude')], default='include', max_length=8)),
                ('report_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='funder_reports.reportfigure')),
            ],
        ),
        migrations.AddField(
            model_name='reportfigure',
            name='report_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='funder_reports.reportsection'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['project', 'is_active'], name='frt_project_active_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['report_template', 'display_order'], name='frs_tmpl_order_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfiguresnapshot',
            index=models.Index(fields=['report_figure', '-generated_at'], name='frsn_figure_time_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfiguresnapshot',
            index=models.Index(fields=['project', 'period_start', 'period_end'], name='frsn_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfigureindicatormapping',
            index=models.Index(fields=['report_figure', 'role'], name='frim_figure_role_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportfigureindicatormapping',
            constraint=models.UniqueConstraint(fields=('report_figure', 'indicator', 'role'), name='uniq_figure_indicator_role'),
        ),
        migrations.AddIndex(
            model_name='reportfigurefilter',
            index=models.Index(fields=['report_figure'], name='frff_figure_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfigure',
            index=models.Index(fields=['report_section', 'display_order'], name='frf_section_order_idx'),
        ),
    ]
