# Generated by Django 4.2.30 on 2026-07-08 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funder_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfiguresnapshot',
            name='filters_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportfiguresnapshot',
            name='period_mode',
            field=models.CharField(blank=True, default='quarter', max_length=16),
        ),
        migrations.AddField(
            model_name='reportfiguresnapshot',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportfiguresnapshot',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfiguresnapshot',
            name='scope_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportfiguresnapshot',
            name='warnings_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
