# Generated by Django 4.2.30 on 2026-07-08 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funder_reports', '0002_reportfiguresnapshot_filters_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Only me'), ('organization', 'My organization'), ('network', 'My hierarchy / network'), ('project', 'Project network'), ('funder', 'Funder / client'), ('public', 'Everyone (system)')], default='private', max_length=16),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['owner', 'visibility'], name='frt_owner_vis_idx'),
        ),
    ]
