# Generated by Django 4.2.30 on 2026-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funder_reports', '0003_reporttemplate_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfigure',
            name='chart_type',
            field=models.CharField(choices=[('achieved_vs_target', 'Achieved vs target bar'), ('grouped_bar', 'Grouped bar'), ('stacked_bar', 'Stacked bar'), ('horizontal_bar', 'Horizontal ranked bar'), ('line', 'Line (quarterly trend)'), ('pie', 'Pie / donut'), ('heatmap', 'Heatmap (age × sex)'), ('cascade', 'Cascade / funnel'), ('table', 'Table'), ('compliance', 'Reporting-compliance matrix')], default='grouped_bar', max_length=32),
        ),
    ]
