# Generated by Django 4.2.30 on 2026-06-12 13:56

from django.db import migrations, models


def backfill_mode_from_params(apps, schema_editor):
    """Smart backfill: existing rows default to 'live', but if a Report or
    ScheduledReport's saved parameters reference a project that is_training=True,
    classify it as training instead of blindly marking it live. On the live DB at
    migration time this flips 0 rows (no saved report referenced a training
    project), so it is a safe no-op there; it protects environments where such a
    report exists. Ambiguous rows are left 'live' (the safe default).
    """
    Report = apps.get_model('analysis', 'Report')
    ScheduledReport = apps.get_model('analysis', 'ScheduledReport')
    Project = apps.get_model('projects', 'Project')
    training_ids = set(Project.objects.filter(is_training=True).values_list('id', flat=True))
    if not training_ids:
        return

    def param_project_id(params):
        if not isinstance(params, dict):
            return None
        raw = params.get('project') or params.get('project_id')
        try:
            return int(raw)
        except (TypeError, ValueError):
            return None

    for model in (Report, ScheduledReport):
        for row in model.objects.all():
            pid = param_project_id(getattr(row, 'parameters', None))
            if pid in training_ids:
                row.mode = 'training'
                row.save(update_fields=['mode'])


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_coordinatortarget'),
        ('projects', '0013_project_is_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('training', 'Training')], db_index=True, default='live', max_length=10),
        ),
        migrations.AddField(
            model_name='savedquery',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('training', 'Training')], db_index=True, default='live', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('training', 'Training')], db_index=True, default='live', max_length=10),
        ),
        migrations.RunPython(backfill_mode_from_params, migrations.RunPython.noop),
    ]
