# Generated by Django 4.2.30 on 2026-05-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_participating_organizations'),
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='events.event'),
        ),
    ]
