# Generated by Django 4.2.30 on 2026-06-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_assessmentquestion_question_and_more'),
        ('respondents', '0002_interaction_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='indicators.question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='indicators.indicator'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('interaction', 'question')},
        ),
    ]
