# Generated by Django 4.2.30 on 2026-04-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('analyzing', 'Analyzing'), ('ready_for_review', 'Ready for Review'), ('processing', 'Processing'), ('validated', 'Validated'), ('completed', 'Completed'), ('imported', 'Imported'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
