# Generated by Django 4.2.30 on 2026-06-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_exportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='mode',
            field=models.CharField(choices=[('live', 'Live'), ('training', 'Training')], db_index=True, default='live', max_length=10),
        ),
    ]
