# Generated by Django 4.2.30 on 2026-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_upload_file_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportjob',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
