"""Excel export for a generated funder-report figure.

Exports exactly what the preview shows — the same filtered, permission-scoped
data the generator returned — plus the applied filters, narrative, warnings and
who/when metadata, so an M&E officer's export is reproducible and never contains
data outside the caller's scope (the caller already scoped the payload).
"""
from __future__ import annotations

from datetime import datetime
from io import BytesIO

from openpyxl import Workbook
from openpyxl.styles import Font


def figure_to_xlsx(payload: dict, *, figure, user) -> bytes:
    wb = Workbook()

    # ── Data sheet: categories × series (+ target / achievement %) ────────────
    ws = wb.active
    ws.title = 'Data'
    bold = Font(bold=True)
    ws['A1'] = f"{payload.get('figure_number', '')} {payload.get('title', figure.title)}".strip()
    ws['A1'].font = Font(bold=True, size=13)

    header = ['Category'] + [s['name'] for s in payload.get('series', [])]
    if payload.get('target'):
        header.append('Target')
    if payload.get('achievement_percent'):
        header.append('Achievement %')
    row0 = 3
    for c, h in enumerate(header, start=1):
        cell = ws.cell(row=row0, column=c, value=h)
        cell.font = bold

    categories = payload.get('categories', [])
    series = payload.get('series', [])
    for i, cat in enumerate(categories):
        r = row0 + 1 + i
        ws.cell(row=r, column=1, value=cat)
        col = 2
        for s in series:
            ws.cell(row=r, column=col, value=s['data'][i] if i < len(s['data']) else None)
            col += 1
        if payload.get('target'):
            ws.cell(row=r, column=col, value=payload['target'][i] if i < len(payload['target']) else None)
            col += 1
        if payload.get('achievement_percent'):
            ap = payload['achievement_percent']
            ws.cell(row=r, column=col, value=ap[i] if i < len(ap) else None)

    totals = payload.get('totals', {})
    tr = row0 + 1 + len(categories) + 1
    ws.cell(row=tr, column=1, value='TOTAL').font = bold
    ws.cell(row=tr, column=2, value=totals.get('total'))

    # ── Context sheet: filters, scope, narrative, warnings, metadata ──────────
    ctx = wb.create_sheet('Context')
    lines = [
        ('Figure', f"{payload.get('figure_number', '')} {payload.get('title', '')}".strip()),
        ('Chart type', payload.get('chart_type', '')),
        ('Period', payload.get('period_label') or f"{payload.get('period_start')} – {payload.get('period_end')}"),
        ('Grouping', payload.get('grouping_dimension', '')),
        ('Secondary grouping', payload.get('secondary_grouping_dimension', '')),
        ('Total', totals.get('total')),
        ('Target', totals.get('target')),
        ('Achievement %', totals.get('achievement_percent')),
        ('Approved data only', 'Yes' if payload.get('scope', {}).get('approved_only', True) else 'No'),
        ('Scope', 'All permitted' if payload.get('scope', {}).get('unrestricted') else
                  f"orgs: {payload.get('scope', {}).get('organization_ids')}"),
        ('Generated by', getattr(user, 'username', '')),
        ('Generated at', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')),
    ]
    for r, (k, v) in enumerate(lines, start=1):
        ctx.cell(row=r, column=1, value=k).font = bold
        ctx.cell(row=r, column=2, value=str(v) if v is not None else '')

    r = len(lines) + 2
    ctx.cell(row=r, column=1, value='Applied filters').font = bold
    for k, v in (payload.get('applied_filters') or {}).items():
        r += 1
        ctx.cell(row=r, column=1, value=k)
        ctx.cell(row=r, column=2, value=str(v))

    r += 2
    ctx.cell(row=r, column=1, value='Narrative').font = bold
    ctx.cell(row=r + 1, column=1, value=payload.get('narrative', ''))

    r += 3
    ctx.cell(row=r, column=1, value='Warnings').font = bold
    for w in payload.get('warnings', []):
        r += 1
        ctx.cell(row=r, column=1, value=f'• {w}')

    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()


def report_to_docx(*, template_name: str, period_label: str, sections: list, user) -> bytes:
    """Render a whole generated report to a Word document: title page, then each
    section with its figures (data table + narrative + warnings). Consumes the
    same normalized, already-scoped figure payloads the dashboard renders."""
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.add_heading(template_name, level=0)
    doc.add_paragraph(f'Reporting period: {period_label}')
    doc.add_paragraph(
        f'Generated by {getattr(user, "username", "")} on '
        f'{datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}'
    )
    doc.add_paragraph(
        'Figures are generated from approved aggregate data within the '
        'generating user\'s permission scope.'
    ).runs[0].italic = True

    for section in sections:
        title = section.get('title', '')
        obj = section.get('objective_label')
        doc.add_heading(f'{obj + ": " if obj else ""}{title}', level=1)
        figures = section.get('figures', [])
        if not figures:
            doc.add_paragraph('No active figures in this section.')
            continue
        for fig in figures:
            heading = f"{fig.get('figure_number', '')} {fig.get('title', '')}".strip()
            doc.add_heading(heading, level=2)

            totals = fig.get('totals', {})
            meta = [f"Total: {totals.get('total')}"]
            if totals.get('target') is not None:
                meta.append(f"Target: {totals.get('target')}")
            if totals.get('achievement_percent') is not None:
                meta.append(f"Achievement: {totals.get('achievement_percent')}%")
            doc.add_paragraph(' · '.join(str(m) for m in meta))

            categories = fig.get('categories', [])
            series = fig.get('series', [])
            if categories and series:
                cols = 1 + len(series) + (1 if fig.get('target') else 0)
                table = doc.add_table(rows=1, cols=cols)
                table.style = 'Light Grid Accent 1'
                hdr = table.rows[0].cells
                hdr[0].text = 'Category'
                for i, s in enumerate(series):
                    hdr[1 + i].text = s['name']
                if fig.get('target'):
                    hdr[-1].text = 'Target'
                for r, cat in enumerate(categories):
                    cells = table.add_row().cells
                    cells[0].text = str(cat)
                    for i, s in enumerate(series):
                        cells[1 + i].text = str(s['data'][r] if r < len(s['data']) else '')
                    if fig.get('target'):
                        tgt = fig['target']
                        cells[-1].text = str(tgt[r] if r < len(tgt) else '')

            if fig.get('narrative'):
                doc.add_paragraph(fig['narrative'])
            for w in fig.get('warnings', []):
                p = doc.add_paragraph(f'⚠ {w}')
                p.runs[0].font.size = Pt(9)

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
