# Generated by Codex on 2026-04-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def ensure_review_fields_exist(apps, schema_editor):
    Aggregate = apps.get_model('aggregates', 'Aggregate')
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(user_app_label, user_model_name)
    table_name = Aggregate._meta.db_table
    existing_columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table_name,
        )
    }

    field_definitions = {
        'status': models.CharField(
            choices=[
                ('draft', 'Draft'),
                ('pending', 'Pending'),
                ('reviewed', 'Reviewed'),
                ('flagged', 'Flagged'),
                ('approved', 'Approved'),
                ('rejected', 'Rejected'),
            ],
            default='pending',
            max_length=20,
        ),
        'reviewed_at': models.DateTimeField(blank=True, null=True),
        'reviewed_by': models.ForeignKey(
            UserModel,
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name='reviewed_aggregates',
        ),
    }

    for field_name, field in field_definitions.items():
        field.set_attributes_from_name(field_name)
        if field.column in existing_columns:
            continue
        schema_editor.add_field(Aggregate, field)


def mark_existing_aggregates_approved(apps, schema_editor):
    Aggregate = apps.get_model('aggregates', 'Aggregate')
    table_name = schema_editor.quote_name(Aggregate._meta.db_table)
    schema_editor.execute(
        f"UPDATE {table_name} "
        "SET status = %s, reviewed_at = created_at, reviewed_by_id = NULL",
        ['approved'],
    )


def unmark_existing_aggregates(apps, schema_editor):
    Aggregate = apps.get_model('aggregates', 'Aggregate')
    table_name = schema_editor.quote_name(Aggregate._meta.db_table)
    schema_editor.execute(
        f"UPDATE {table_name} "
        "SET status = %s, reviewed_at = NULL, reviewed_by_id = NULL",
        ['pending'],
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregates', '0002_aggregate_period_start_index'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_review_fields_exist, migrations.RunPython.noop),
                migrations.RunPython(mark_existing_aggregates_approved, unmark_existing_aggregates),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='aggregate',
                    name='status',
                    field=models.CharField(choices=[
                        ('draft', 'Draft'),
                        ('pending', 'Pending'),
                        ('reviewed', 'Reviewed'),
                        ('flagged', 'Flagged'),
                        ('approved', 'Approved'),
                        ('rejected', 'Rejected'),
                    ], default='pending', max_length=20),
                ),
                migrations.AddField(
                    model_name='aggregate',
                    name='reviewed_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='aggregate',
                    name='reviewed_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_aggregates', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
