# Generated by Django 4.2.30 on 2026-05-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0003_aggregate_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='copy_paste_verified',
            field=models.BooleanField(default=False, help_text='Set by admin after confirming that identical values across indicators are genuinely correct. Skips future copy-paste detection for this record.'),
        ),
    ]
