# Generated by Django 4.2.30 on 2026-06-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_assessmentquestion_question_and_more'),
        ('projects', '0018_backfill_assigned_users'),
        ('organizations', '0003_add_dashboard_config'),
        ('aggregates', '0004_copy_paste_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('is_training', models.BooleanField(default=False)),
                ('primary', models.CharField(default='All', max_length=128)),
                ('secondary', models.CharField(default='All', max_length=64)),
                ('band', models.CharField(default='Total', max_length=64)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='aggregates.aggregate')),
                ('canonical_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indicators.indicator')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='indicators.indicator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['canonical_indicator', 'status', 'is_training'], name='aggfact_ind_status_idx'), models.Index(fields=['project', 'organization', 'period_start'], name='aggfact_scope_period_idx'), models.Index(fields=['status', 'is_training', 'period_start'], name='aggfact_status_period_idx')],
            },
        ),
    ]
