# Generated by Django 4.2.30 on 2026-06-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0005_aggregatefact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatefact',
            name='band',
            field=models.CharField(default='Total', max_length=255),
        ),
        migrations.AlterField(
            model_name='aggregatefact',
            name='primary',
            field=models.CharField(default='All', max_length=512),
        ),
        migrations.AlterField(
            model_name='aggregatefact',
            name='secondary',
            field=models.CharField(default='All', max_length=255),
        ),
    ]
