# Generated by Django 4.2.30 on 2026-06-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # DataQualityScore.project only needs the projects table; pin to 0019 (an
        # ancestor of 0020) so this matches what's applied LIVE and a future
        # full-stack deploy migrates cleanly. See parity-hotfix deploy notes.
        ('projects', '0019_workbook_layout'),
        ('aggregates', '0006_alter_aggregatefact_band_alter_aggregatefact_primary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('organization', 'Organization'), ('coordinator', 'Coordinator'), ('project', 'Project'), ('national', 'National')], max_length=16)),
                ('scope_id', models.IntegerField(blank=True, null=True)),
                ('scope_label', models.CharField(blank=True, default='', max_length=255)),
                ('mode', models.CharField(choices=[('live', 'Live'), ('training', 'Training')], default='live', max_length=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('label', models.CharField(blank=True, default='', max_length=32)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('run_label', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_scores', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-score'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id', '-created_at'], name='dqscore_scope_idx'), models.Index(fields=['mode', 'scope_type', '-created_at'], name='dqscore_mode_scope_idx')],
            },
        ),
    ]
