# Generated by Django 4.2.30 on 2026-07-08 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectindicator_target_source_indicator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aggregates', '0008_aggregate_scope_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField(help_text='Botswana fiscal START year, e.g. 2025 for FY 2025/26.')),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField()),
                ('submission_opens', models.DateTimeField(blank=True, null=True)),
                ('submission_closes', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('allow_late_reporting', models.BooleanField(default=False)),
                ('late_reporting_opens', models.DateTimeField(blank=True, null=True)),
                ('late_reporting_closes', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reporting_periods', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='projects.project')),
            ],
            options={
                'ordering': ['-fiscal_year', '-quarter', 'project_id'],
                'indexes': [models.Index(fields=['project', 'status'], name='rp_project_status_idx'), models.Index(fields=['project', 'fiscal_year', 'quarter'], name='rp_project_fyq_idx'), models.Index(fields=['status'], name='rp_status_idx'), models.Index(fields=['fiscal_year', 'quarter'], name='rp_fyq_idx'), models.Index(fields=['submission_opens'], name='rp_sub_opens_idx'), models.Index(fields=['submission_closes'], name='rp_sub_closes_idx'), models.Index(fields=['coverage_start', 'coverage_end'], name='rp_coverage_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportingperiod',
            constraint=models.UniqueConstraint(fields=('project', 'fiscal_year', 'quarter'), name='uniq_reporting_period_project_fy_quarter'),
        ),
    ]
