# Generated by Django 4.2.30 on 2026-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0009_reportingperiod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggregate',
            options={'ordering': ['-period_start', '-id']},
        ),
        migrations.AlterModelOptions(
            name='dataqualityscore',
            options={'ordering': ['-created_at', '-score', '-id']},
        ),
        migrations.AlterModelOptions(
            name='reportingperiod',
            options={'ordering': ['-fiscal_year', '-quarter', 'project_id', 'id']},
        ),
    ]
