# Generated by Django 4.2.30 on 2026-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsoMappingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False)),
                ('respondent_type', models.CharField(choices=[('cso', 'Health Service Civil Society Organisation'), ('coordinating_body', 'Coordinating body, umbrella body or network'), ('strategic_structure', 'DAC, DHMT, Government or other strategic-level structure')], max_length=32)),
                ('responding_entity', models.CharField(max_length=255)),
                ('respondent_name', models.CharField(max_length=255)),
                ('respondent_position', models.CharField(blank=True, max_length=255)),
                ('respondent_phone', models.CharField(blank=True, max_length=64)),
                ('respondent_email', models.EmailField(blank=True, max_length=254)),
                ('primary_district', models.CharField(blank=True, max_length=255)),
                ('information_confirmed', models.BooleanField(default=False)),
                ('additional_comments', models.TextField(blank=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('form_version', models.CharField(blank=True, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CSO mapping submission',
                'verbose_name_plural': 'CSO mapping submissions',
                'ordering': ['-submitted_at', '-id'],
                'indexes': [models.Index(fields=['respondent_type'], name='cso_mapping_respond_908acb_idx'), models.Index(fields=['-submitted_at'], name='cso_mapping_submitt_25cf26_idx')],
            },
        ),
    ]
