# Generated by Django 4.2.30 on 2026-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_mapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csomappingsubmission',
            name='client_submission_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='csomappingsubmission',
            name='public_reference',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
