# Generated by Django 4.2.30 on 2026-08-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cso_mapping', '0002_csomappingsubmission_client_submission_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsoMappingDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('client_submission_id', models.UUIDField(blank=True, null=True)),
                ('respondent_type', models.CharField(blank=True, max_length=32)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('form_version', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='cso_mapping.csomappingsubmission')),
            ],
            options={
                'verbose_name': 'CSO mapping draft',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['expires_at'], name='cso_mapping_expires_2fc9d6_idx')],
            },
        ),
    ]
