# Generated by Django 4.2.30 on 2026-08-05 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cso_mapping', '0003_csomappingdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsoMappingSchemaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField()),
                ('version_label', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CSO mapping schema version',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='csomappingschemaversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='cso_mapping_one_active_schema'),
        ),
    ]
