# Generated by Django 4.2.30 on 2026-08-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cso_mapping', '0004_csomappingschemaversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csomappingsubmission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='csomappingsubmission',
            name='location_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='csomappingsubmission',
            name='location_capture_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='csomappingsubmission',
            name='location_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csomappingsubmission',
            name='location_flag_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='csomappingsubmission',
            name='location_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csomappingsubmission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
