# Generated by Django 4.2.28 on 2026-02-06 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_alter_organization_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logic_rules', models.JSONField(blank=True, default=dict, help_text='Conditional display rules')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('yes_no', 'Yes/No'), ('number', 'Number'), ('percentage', 'Percentage'), ('text', 'Text'), ('select', 'Single Select'), ('multiselect', 'Multi Select'), ('date', 'Date'), ('multi_int', 'Multiple Integers')], default='number', max_length=20)),
                ('category', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('economic', 'Economic'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='e.g., people, sessions, %', max_length=50)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select types')),
                ('sub_labels', models.JSONField(blank=True, default=list, help_text='Labels for multi-int fields')),
                ('aggregation_method', models.CharField(choices=[('sum', 'Sum'), ('average', 'Average'), ('count', 'Count'), ('latest', 'Latest')], default='sum', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_indicators', to=settings.AUTH_USER_MODEL)),
                ('organizations', models.ManyToManyField(blank=True, related_name='indicators', to='organizations.organization')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('condition_value', models.JSONField(blank=True, help_text='Value that triggers display', null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.assessment')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='indicators.assessmentindicator')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('assessment', 'indicator')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='indicators',
            field=models.ManyToManyField(related_name='assessments', through='indicators.AssessmentIndicator', to='indicators.indicator'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='organizations.organization'),
        ),
    ]
