# Generated by Django 4.2.28 on 2026-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.CharField(choices=[('hiv_prevention', 'HIV Prevention'), ('ncd', 'Non-Communicable Diseases'), ('events', 'Events')], default='hiv_prevention', max_length=30),
        ),
    ]
