# Generated by Codex on 2026-04-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0002_alter_indicator_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_indicator_aliases', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='indicators.indicator')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='indicatoralias',
            constraint=models.UniqueConstraint(fields=('indicator', 'normalized_name'), name='unique_indicator_alias_per_indicator'),
        ),
        migrations.AddConstraint(
            model_name='indicatoralias',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('normalized_name',), name='unique_active_indicator_alias_name'),
        ),
    ]
