# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicatoralias'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentindicator',
            name='help_text',
            field=models.TextField(blank=True, help_text='Optional helper text shown below the question'),
        ),
        migrations.AddField(
            model_name='assessmentindicator',
            name='question_text',
            field=models.CharField(blank=True, help_text='Question prompt shown in the assessment form', max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentindicator',
            name='response_options',
            field=models.JSONField(blank=True, default=list, help_text='Question-specific options for select and multiselect types'),
        ),
        migrations.AddField(
            model_name='assessmentindicator',
            name='response_sub_labels',
            field=models.JSONField(blank=True, default=list, help_text='Question-specific labels for multi-integer responses'),
        ),
        migrations.AddField(
            model_name='assessmentindicator',
            name='response_type',
            field=models.CharField(blank=True, choices=[('yes_no', 'Yes/No'), ('number', 'Number'), ('percentage', 'Percentage'), ('text', 'Text'), ('select', 'Single Select'), ('multiselect', 'Multi Select'), ('date', 'Date'), ('multi_int', 'Multiple Integers')], default='', help_text='Optional question response type override', max_length=20),
        ),
    ]
