# Generated by Codex on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_assessmentindicator_question_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentindicator',
            name='aggregate_match_values',
            field=models.JSONField(blank=True, default=list, help_text='Values that should count when aggregate mode uses selected values'),
        ),
        migrations.AddField(
            model_name='assessmentindicator',
            name='aggregate_mode',
            field=models.CharField(choices=[('none', 'No automatic roll-up'), ('count_all', 'Count each answered response'), ('count_selected', 'Count selected values'), ('sum_numeric', 'Use numeric answer total')], default='none', help_text='How this question should contribute to the linked indicator total', max_length=20),
        ),
    ]
