# Generated by Django 4.2.30 on 2026-06-01 09:09
#
# The aggregate_disaggregation_config column already exists in the production
# database (it was added out-of-band before this migration existed), but it was
# never declared on the model or in any migration. To reconcile this safely on
# BOTH existing databases (column present) and freshly-built databases (column
# absent), we update Django's migration state with the field while performing an
# idempotent "ADD COLUMN IF NOT EXISTS" at the database level. On production this
# is a no-op (column already there); on a new DB it creates the column.

from django.db import migrations, models


def add_disaggregation_config_column(apps, schema_editor):
    """Idempotently add the column on whatever backend we are running on.

    Postgres production already has this column (added out-of-band), so we use
    ADD COLUMN IF NOT EXISTS there. SQLite (used for the test database and local
    dev) does not support IF NOT EXISTS, so we add it plainly and tolerate the
    "duplicate column" error in case it is already present.
    """
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE indicators_indicator "
            "ADD COLUMN IF NOT EXISTS aggregate_disaggregation_config "
            "jsonb NOT NULL DEFAULT '{}'::jsonb;"
        )
    else:
        try:
            schema_editor.execute(
                "ALTER TABLE indicators_indicator "
                "ADD COLUMN aggregate_disaggregation_config text NOT NULL DEFAULT '{}';"
            )
        except Exception:
            # Column already exists on this backend; nothing to do.
            pass


def drop_disaggregation_config_column(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE indicators_indicator "
            "DROP COLUMN IF EXISTS aggregate_disaggregation_config;"
        )
    else:
        try:
            schema_editor.execute(
                "ALTER TABLE indicators_indicator "
                "DROP COLUMN aggregate_disaggregation_config;"
            )
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_indicator_deduplication'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='indicator',
                    name='aggregate_disaggregation_config',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    add_disaggregation_config_column,
                    drop_disaggregation_config_column,
                ),
            ],
        ),
    ]
