# Generated by Django 4.2.30 on 2026-06-01 09:09
#
# The aggregate_disaggregation_config column already exists in the production
# database (it was added out-of-band before this migration existed), but it was
# never declared on the model or in any migration. To reconcile this safely on
# BOTH existing databases (column present) and freshly-built databases (column
# absent), we update Django's migration state with the field while performing an
# idempotent "ADD COLUMN IF NOT EXISTS" at the database level. On production this
# is a no-op (column already there); on a new DB it creates the column.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_indicator_deduplication'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='indicator',
                    name='aggregate_disaggregation_config',
                    field=models.JSONField(blank=True, default=dict),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE indicators_indicator "
                        "ADD COLUMN IF NOT EXISTS aggregate_disaggregation_config "
                        "jsonb NOT NULL DEFAULT '{}'::jsonb;"
                    ),
                    reverse_sql=(
                        "ALTER TABLE indicators_indicator "
                        "DROP COLUMN IF EXISTS aggregate_disaggregation_config;"
                    ),
                ),
            ],
        ),
    ]
