# Generated by Django 4.2.30 + hand-edited to copy AssessmentIndicator data
# into the new Question / AssessmentQuestion bank before dropping the old model.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_assessment_indicators_to_questions(apps, schema_editor):
    """Convert each existing AssessmentIndicator into a bank Question + placement.

    One Question is created per AssessmentIndicator (no dedup), preserving its
    prompt, type, options and — crucially — its existing indicator link and
    aggregate config so reporting roll-ups keep working. Org links are carried
    over from the indicator. depends_on is rewired in a second pass.
    """
    AssessmentIndicator = apps.get_model('indicators', 'AssessmentIndicator')
    Question = apps.get_model('indicators', 'Question')
    AssessmentQuestion = apps.get_model('indicators', 'AssessmentQuestion')

    ai_to_aq = {}
    for ai in AssessmentIndicator.objects.all():
        indicator = ai.indicator
        question = Question.objects.create(
            text=(ai.question_text or (indicator.name if indicator else 'Question'))[:255],
            code=None,
            help_text=ai.help_text or '',
            response_type=ai.response_type or (indicator.type if indicator else 'text'),
            options=ai.response_options or (indicator.options if indicator else []) or [],
            sub_labels=ai.response_sub_labels or (indicator.sub_labels if indicator else []) or [],
            category=(indicator.category if indicator else '') or '',
            indicator_id=ai.indicator_id,
            aggregate_mode=ai.aggregate_mode or 'none',
            aggregate_match_values=ai.aggregate_match_values or [],
            is_active=True,
        )
        if indicator is not None:
            org_ids = list(indicator.organizations.values_list('id', flat=True))
            if org_ids:
                question.organizations.set(org_ids)

        aq = AssessmentQuestion.objects.create(
            assessment_id=ai.assessment_id,
            question=question,
            order=ai.order,
            is_required=ai.is_required,
            condition_value=ai.condition_value,
        )
        ai_to_aq[ai.id] = aq

    # Second pass: rewire depends_on (AssessmentIndicator self-FK -> AssessmentQuestion).
    for ai in AssessmentIndicator.objects.exclude(depends_on__isnull=True):
        child = ai_to_aq.get(ai.id)
        parent = ai_to_aq.get(ai.depends_on_id)
        if child and parent:
            child.depends_on = parent
            child.save(update_fields=['depends_on'])


def noop_reverse(apps, schema_editor):
    # One-way data migration; reversing drops the new tables via the schema ops.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0008_indicator_aggregate_disaggregation_config'),
    ]

    operations = [
        # 1) Create the new bank models (with all FKs) so data can be copied in.
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Question prompt shown to the data collector', max_length=255)),
                ('code', models.CharField(blank=True, help_text='Optional stable code used for seeding/import references', max_length=50, null=True, unique=True)),
                ('help_text', models.TextField(blank=True, help_text='Optional helper text shown below the question')),
                ('response_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('number', 'Number'), ('percentage', 'Percentage'), ('text', 'Text'), ('select', 'Single Select'), ('multiselect', 'Multi Select'), ('date', 'Date'), ('multi_int', 'Multiple Integers')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select / multiselect questions')),
                ('sub_labels', models.JSONField(blank=True, default=list, help_text='Labels for multi-integer questions')),
                ('category', models.CharField(blank=True, choices=[('hiv_prevention', 'HIV Prevention'), ('ncd', 'Non-Communicable Diseases'), ('mental_health', 'Mental Health'), ('gbv', 'GBV'), ('sti', 'STI'), ('trainings', 'Trainings'), ('media', 'Media'), ('events', 'Events')], default='', max_length=30)),
                ('aggregate_mode', models.CharField(choices=[('none', 'No automatic roll-up'), ('count_all', 'Count each answered response'), ('count_selected', 'Count selected values'), ('sum_numeric', 'Use numeric answer total')], default='none', help_text='How this question contributes to the linked indicator total', max_length=20)),
                ('aggregate_match_values', models.JSONField(blank=True, default=list, help_text='Values that count when aggregate mode uses selected values')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(blank=True, help_text='Optional indicator this question contributes to for reporting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='indicators.indicator')),
                ('organizations', models.ManyToManyField(blank=True, help_text='Leave empty for a cross-cutting question visible to all organizations', related_name='questions', to='organizations.organization')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('condition_value', models.JSONField(blank=True, help_text='Value that triggers display', null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.assessment')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='indicators.assessmentquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(related_name='assessments', through='indicators.AssessmentQuestion', to='indicators.question'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('assessment', 'question')},
        ),
        # 2) Copy existing AssessmentIndicator rows into the bank.
        migrations.RunPython(copy_assessment_indicators_to_questions, noop_reverse),
        # 3) Drop the old through model / M2M.
        migrations.RemoveField(
            model_name='assessment',
            name='indicators',
        ),
        migrations.DeleteModel(
            name='AssessmentIndicator',
        ),
    ]
