# Generated by Django 4.2.30 on 2026-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_indicator_denominator_indicator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'ordering': ['category', 'name', 'id']},
        ),
    ]
