# Generated by Django 4.2.30 on 2026-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
