# Generated by Django 4.2.30 on 2026-07-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_flag_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
