# Generated by Django 4.2.28 on 2026-02-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_socialpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialservice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='socialservice',
            name='respondent',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='SocialService',
        ),
    ]
