# Generated by Django 4.2.28 on 2026-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_socialservice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
