# Generated by Django 4.2.28 on 2026-02-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_type'),
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi Select'), ('boolean', 'Yes/No')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select fields')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_fields', to='organizations.organization')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('income_level', models.CharField(blank=True, max_length=100)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('health_status', models.CharField(blank=True, max_length=100)),
                ('disabilities', models.TextField(blank=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='respondents.respondent')),
            ],
        ),
    ]
