# Generated by Django 4.2.29 on 2026-04-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'M&E Manager'), ('officer', 'M&E Officer'), ('collector', 'Data Collector'), ('client', 'Client')], default='officer', max_length=20),
        ),
    ]
