# Generated by Django 4.2.30 on 2026-06-10 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_home_dashboard_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('actions', models.JSONField(default=list)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'module'],
            },
        ),
        migrations.AddConstraint(
            model_name='usermodulepermission',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_user_module_permission'),
        ),
    ]
