# Generated by Django 4.2.30 on 2026-06-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodulepermission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='environment_access',
            field=models.CharField(choices=[('both', 'Live and Training'), ('live', 'Live only'), ('training', 'Training only')], default='both', max_length=10),
        ),
    ]
