# Generated by Django 4.2.30 on 2026-07-24 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options_alter_useractivity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialityAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('training', 'Training')], max_length=10)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidentiality_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at', '-id'],
                'indexes': [models.Index(fields=['user', 'version'], name='users_confi_user_id_944e7b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='confidentialityacknowledgement',
            constraint=models.UniqueConstraint(fields=('user', 'version'), name='unique_user_confidentiality_version'),
        ),
    ]
