# Generated by Django 4.2.30 on 2026-06-10 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_backfill_assigned_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_add_dashboard_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('review', 'Review'), ('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('import', 'Import'), ('export', 'Export'), ('assign', 'Assign'), ('login', 'Login'), ('logout', 'Logout')], max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='organizations.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['action'], name='audit_action_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_object_idx'), models.Index(fields=['actor'], name='audit_actor_idx')],
            },
        ),
    ]
