# Generated by Django 4.2.30 on 2026-06-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditevent_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('review', 'Review'), ('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('import', 'Import'), ('export', 'Export'), ('assign', 'Assign'), ('login', 'Login'), ('logout', 'Logout'), ('backup_generated', 'Backup generated'), ('backup_downloaded', 'Backup downloaded'), ('backup_download_reminder_sent', 'Backup download reminder sent'), ('backup_uploaded', 'Backup uploaded'), ('backup_restored', 'Backup restored'), ('restore_failed', 'Restore failed'), ('environment_override', 'Environment override')], max_length=32),
        ),
    ]
