# Generated by Django 4.2.30 on 2026-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('review', 'Review'), ('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag'), ('unflag', 'Unflag'), ('import', 'Import'), ('export', 'Export'), ('view', 'View'), ('assign', 'Assign'), ('login', 'Login'), ('logout', 'Logout'), ('backup_generated', 'Backup generated'), ('backup_downloaded', 'Backup downloaded'), ('backup_download_reminder_sent', 'Backup download reminder sent'), ('backup_uploaded', 'Backup uploaded'), ('backup_restored', 'Backup restored'), ('restore_failed', 'Restore failed'), ('environment_override', 'Environment override'), ('reporting_window_override', 'Reporting window override'), ('reporting_period_created', 'Reporting period created'), ('reporting_period_updated', 'Reporting period updated'), ('reporting_scheduled', 'Reporting scheduled'), ('reporting_opened', 'Reporting opened'), ('reporting_closed', 'Reporting closed'), ('reporting_reopened', 'Reporting reopened'), ('reporting_archived', 'Reporting archived'), ('late_reporting_enabled', 'Late reporting enabled'), ('late_reporting_disabled', 'Late reporting disabled'), ('reporting_submission_blocked', 'Reporting submission blocked')], max_length=32),
        ),
    ]
